name: Sync All Branches

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync all upstream branches
        run: |
          git remote add upstream https://github.com/mohamedali-gazzar/PL-Website.git
          git fetch upstream --prune

          git for-each-ref --format='%(refname:short)' refs/remotes/upstream/ | while read branch; do
            branch=${branch#upstream/}

            if [ "$branch" != "HEAD" ]; then
              git push origin "refs/remotes/upstream/$branch:refs/heads/$branch" --force
            fi
          done
