// Low-voltage project reference list — the curated "Updated Project Name"
// set provided by Powerline (LV (1).xlsx). Shared across all LV product
// pages' Track Record section. Mixed Arabic/English names; the component
// only renders `name`.  ("سيناء الوطنية للصناعات البلاستيكية" → "NSPI".)
export const lvProjects = [
  { name: "Bay Village" },
  { name: "Banha Teaching Hospital" },
  { name: "SODIC June Parcel 5" },
  { name: "Al Santa Hospital" },
  { name: "Mountain View 1.1" },
  { name: "DP World Sokhna" },
  { name: "R3 New Capital City" },
  { name: "Amorada Park View" },
  { name: "Go Heliopolis" },
  { name: "TEDA" },
  { name: "Gardinia 2 Compound" },
  { name: "Cancer Treatment Center in Ismaelia" },
  { name: "Durrat Al Karaz" },
  { name: "Il Bosco" },
  { name: "NSPI" },
  { name: "ODFI" },
  { name: "EVER Grow" },
  { name: "SCZone" },
  { name: "SEDICO Pharmaceutical" },
  { name: "Jezzine Alex West" },
  { name: "Al Ghali University Hospital" },
  { name: "South Gate New Cairo" },
  { name: "Toshka - Phase 2" },
  { name: "The Avenue Mall - New Capital" },
  { name: "Egypt International Olympic City" },
  { name: "Craft Zone" },
  { name: "Nile For Plastic Industries" },
  { name: "SODIC VYE" },
  { name: "Golden Fish" },
  { name: "NPK Fertilizer Plant" },
  { name: "DEJOYA" },
  { name: "BRT" },
  { name: "I City October" },
  { name: "The Estates - SODIC" },
  { name: "Forsan Al Behar Compound" },
  { name: "Emerits Oil - Chemicals" },
  { name: "Trivium" },
  { name: "Al Hadiqa Ad Dawlia" },
  { name: "Qena Oncology Center" },
  { name: "Copad Egypt for the pharmacutical supplments" },
  { name: "Delta El Nile for Industries" },
  { name: "Bir Al-Abd Hospital" },
  { name: "Be Industrial" },
  { name: "Dejoya Mall 2" },
  { name: "Al Amer Tex" },
  { name: "Bo Sands - The Marq" },
  { name: "Neom Paper" },
  { name: "Green Yard 2" },
  { name: "Givaudan Egypt" },
  { name: "Bakka Clothing" },
  { name: "Concordia Mall - Data Center" },
  { name: "Nile Glass" },
  { name: "EgyDenim Factory" },
  { name: "Sodic East Club" },
  { name: "Eastern Company" },
  { name: "Amana Plast Factory" },
  { name: "Stein Crete Factory" },
  { name: "New Cotton Factory" },
  { name: "Alcon Block - Reacst Factory" },
  { name: "Akhmim Al Jadida Reform And Rehabilition Center" },
  { name: "Benha Sc" },
  { name: "Tiba Perfumes" },
  { name: "Egyptian Countryside Development" },
  { name: "University Hospital in Benha" },
  { name: "Portsaid Psychiatric Hospital" },
  { name: "Republican Guard Officers Club" },
  { name: "Carrefour - Fifth Square Mall" },
  { name: "Royal Mall" },
  { name: "Negm El Arab for Household Utensils" },
  { name: "United Glass Company - UGC" },
  { name: "Eastown - Sodic" },
  { name: "Al Orman Garden" },
  { name: "The Mummification Musium" },
  { name: "SCZone Utilities" },
  { name: "Abbasia Fever Hospital" },
  { name: "Karmell Hub - Sodic VYE" },
  { name: "Hacienda West – North Coast" },
  { name: "Happy Foods Egypt" },
];
