// Project reference list for the MV switchgear (Schneider MCset) track record,
// from the Powerline "MVSWG" sheet (New English Name column). One duplicate
// (AROMA) collapsed to one. The component only renders `name`.
export const mvswgProjects = [
  { name: "Al Oubor Hospital" },
  { name: "NewSamco" },
  { name: "National Organization for Drug Control and Research" },
  { name: "Al Esraa Pharmacutical Obtima" },
  { name: "ACRO" },
  { name: "Power Copper" },
  { name: "AROMA" },
  { name: "Nile For Plastic Industries" },
  { name: "Sholan Somabay resort" },
  { name: "TEDA" },
  { name: "Katameya coast" },
  { name: "Bay Village Sahl Hasheesh" },
  { name: "New Baby Factory" },
  { name: "Al Zayed For Metal Industries" },
  { name: "MIDEA" },
  { name: "LAKE VIEW Boutiques" },
  { name: "SCZONE" },
  { name: "Al Batros Aqua Park" },
  { name: "Al Sonya Textile" },
  { name: "Nile Fiber" },
  { name: "Golden Fesh" },
  { name: "Ameres Internationa" },
  { name: "SCZone - Sokhna Port" },
  { name: "Al Santa Hospital" },
  { name: "Mall 360" },
  { name: "Kahramana Hotel" },
  { name: "Al Safwa - Sadat City" },
  { name: "EVER Grow" },
  { name: "Nozha Beach" },
  { name: "Al Dawlia For Ceramic Industries" },
  { name: "Al Zahra Tex" },
];
