// PRAL (Air-insulated Ring Main Unit) project reference list — the updated
// "New Name" set provided by Powerline (PRAL.xlsx), shown in the PRAL
// product page's Track Record section. The component only renders `name`.
export const pralProjects = [
  { name: "Amyris International" },
  { name: "Multi M Textile" },
  { name: "Green 6" },
  { name: "Port Of Al Dekhila" },
  { name: "Mamsha Ahl Misr" },
  { name: "Alamin Towers - Tower 3" },
  { name: "Newton Education Service" },
  { name: "Rajac School" },
  { name: "National Bank Of Egypt" },
  { name: "Valley Higher Institute" },
  { name: "Nozha Language School - Higaz" },
  { name: "Nozha Language School - Ismailia Road" },
  { name: "Rosana Mall" },
  { name: "Downtown Mall - Sohag" },
  { name: "Al Khamayel Club" },
  { name: "National Organization for Drug & and control research" },
  { name: "Aswan Prison" },
  { name: "The International Park" },
  { name: "Kandile Egypt" },
  { name: "Nasa Mattress" },
  { name: "Agrovita for Food Industries" },
  { name: "Lotus Garments Co." },
  { name: "No Limits Furnature" },
  { name: "Abu Auf Factory" },
  { name: "BOEN Shoes Factory" },
  { name: "Al Mahy for Food Industries" },
  { name: "Dobby Tex" },
  { name: "ASALA Mall" },
  { name: "Eagle Pack" },
  { name: "EnergyLux" },
  { name: "Petco Plast" },
  { name: "Al Hadarat Club" },
  { name: "Trofico Pharma" },
  { name: "Interpharma Corporation-IPC" },
  { name: "Art Corner" },
  { name: "Mini Top Factory" },
  { name: "Multi Pack" },
  { name: "Egyptian Saudi Co. for Chocolate production" },
  { name: "Harmoni School" },
  { name: "NewSamco" },
  { name: "KMT Pharma" },
  { name: "Kraft Pack" },
  { name: "The American School ASE" },
  { name: "El Hoda Trade & Supplies" },
  { name: "Great Foods Original" },
  { name: "Pharma Click" },
  { name: "Al Fahd Furnature" },
  { name: "Sohag Mills" },
  { name: "Dejoya" },
  { name: "Al Marasim International School" },
  { name: "Golden Modern School" },
  { name: "ASH For Construction" },
  { name: "Mediterraneo Egypt" },
  { name: "Sermix Redy Mix Concrete" },
  { name: "B7 Mall" },
  { name: "Allulua School" },
];
