// Project reference list for PSEC (SF6 Ring Main Unit), extracted from the
// Powerline "P SEC RMU" reference PDF. Mixed Arabic/English client names;
// the component only renders `name`. Auto-extracted — spellings worth a review.
export const psecProjects = [
  { name: "النيل للبلاستيك" },
  { name: "AROMA - AKAM El Rajhi" },
  { name: "جامعة السادات" },
  { name: "مشروع امورادا بارك فيو" },
  { name: "شركة المصرية إلكتريك" },
  { name: "تطوير مستشفى أورام الإسماعيلية" },
  { name: "Pharma Overseas Almaza" },
  { name: "SHOLAN SOMABAY MV NETWORK" },
  { name: "الفارس العربي للملابس الجاهزة" },
  { name: "المؤسسة المتحدة للتوريدات والصناعات الهندسية" },
  { name: "جاردينيا 2" },
  { name: "Soma Bay - MARINA" },
  { name: "شركة صن تكس" },
  { name: "Katameya Coast" },
  { name: "الشريف الحرارية المصرية" },
  { name: "Accrow" },
  { name: "PAY CENTRAIL" },
  { name: "محطات برج العرب / وادي النطرون / العاشر من رمضان / انشاص" },
  { name: "الياسمين بلاس" },
  { name: "مول البستان" },
  { name: "مجمع النيابات الإدارية بالفيوم" },
  { name: "بطريركية الأقباط الإنجيلية" },
  { name: "مشروع إنشاء الموقف الإقليمي لمدينة المنيا الجديدة" },
  { name: "Atom Mall" },
  { name: "المركز الثقافي العربي الإنجليزي" },
  { name: "إنارة سور مطار شرم الشيخ الدولي" },
  { name: "Al Nozha Beach - RMU" },
  { name: "الجامعة الألمانية بالقاهرة" },
  { name: "Asten College School – Taj City" },
  { name: "Kinda Mall" },
  { name: "مستشفى بني عبيد" },
  { name: "منتجع فيتونا الساحل الشمالي" },
  { name: "Jungle Aqua Park" },
  { name: "أكوا مارين الغردقة" },
  { name: "Albatros Hurghada" },
  { name: "Radamis Hotels - Sharm El-Sheikh" },
  { name: "فندق تيتانا - المرحلة الثانية" },
  { name: "مشروع بيتش سفاري مرسى علم" },
  { name: "Sale Sucre" },
  { name: "Noor Food Industry Factory" },
  { name: "Mina Plast" },
  { name: "نيوتك" },
  { name: "مشروع المنطقة الاقتصادية - العين السخنة (360)" },
  { name: "Lake View Boutique" },
  { name: "Aroma Phase 3&4" },
  { name: "Palm Beach" },
  { name: "I City New Cairo" },
  { name: "Nissan Gantry" },
  { name: "كنيسة السيدة العذراء والقديس اسانسيوس بمدينة نصر" },
  { name: "ميبكو" },
  { name: "هنجر A9 - ميناء سفاجا" },
  { name: "مصنع الأمين للجيلاتين" },
  { name: "مول الزيني" },
  { name: "مصنع كربونات الكالسيوم" },
  { name: "مصنع جراند" },
  { name: "طيبة للعطور" },
  { name: "مصنع الحازم لصناعة الوصلات والمواسير البلاستيك" },
  { name: "ديسكفري للتعدين" },
  { name: "مصنع كنعان تكس" },
  { name: "مول شيراتون" },
  { name: "مطابع العامرية الجديدة" },
  { name: "الجامعة الأهلية" },
  { name: "أمانة بلاست" },
  { name: "الشيف للصناعات الغذائية" },
  { name: "شركة نون للطباعة والتغليف" },
  { name: "اكتوبر فارما" },
  { name: "مدرسة بايونير إديوكيشن" },
  { name: "Badya" },
  { name: "قرية زمردة - الساحل الشمالي" },
  { name: "El Gouna" },
  { name: "مستشفى الشرطة بالأكاديمية" },
  { name: "كلية الفنون الجميلة - جامعة النهضة ببني سويف" },
  { name: "النيل لصناعة البلاستيك" },
  { name: "Tirana Aqua Park - Radamis" },
  { name: "ROSETEX SAHL HASHISH" },
  { name: "Mardini" },
  { name: "ICON - 5th Settlement" },
  { name: "West Gate" },
  { name: "فندق كهرمانة" },
  { name: "بنك مصر - فرع مصطفى كامل" },
  { name: "تجميع سيارات القصراوي" },
  { name: "إيمرتس أويل للصناعات الكيماوية" },
  { name: "مول كراون بلازا - القاهرة الجديدة" },
  { name: "Amer Group - Porto Heliopolis" },
  { name: "شركة وثاق للتأمين التكافلي - مصر" },
  { name: "مبنى مقر جهاز مستقبل مصر - ألماظة" },
  { name: "الشركة الاقتصادية للصناعة الغذائية - كمارا" },
  { name: "Amrecana" },
  { name: "Moderna Hotel" },
  { name: "لايت شارم للاستثمار السياحي" },
  { name: "AZHA" },
  { name: "الجامعة التكنولوجية (CSU)" },
  { name: "Harmony" },
  { name: "مجمع بولاريس الدولية - منطقة المطورين الصناعية" },
  { name: "South Camp Sharm El Sheikh" },
  { name: "فندق كليوباترا" },
  { name: "باي فيليج" },
  { name: "SCZONE 6 RMU" },
  { name: "Tirana City 2" },
  { name: "شركة السنهوري للمنظفات الصناعية والأسمدة" },
  { name: "CAVO" },
];
