// PSEC (SF6 Ring Main Unit) project reference list — the updated "English
// Commercial Name" set provided by Powerline (PSEC.xlsx), shown in the PSEC
// product page's Track Record section. Duplicate rows in the source were
// collapsed to one. The component only renders `name`.
export const psecProjects = [
  { name: "Nile For Plastic Industries" },
  { name: "AROMA Resort" },
  { name: "University of Sadat City" },
  { name: "Amorada Park View" },
  { name: "Egiptian Electric Co." },
  { name: "Cancer Treatment Center in Ismaielia" },
  { name: "Pharma Overseas" },
  { name: "Sholan SOMABAY" },
  { name: "Gardenia 2" },
  { name: "SOMABAY - Marina" },
  { name: "SunTex" },
  { name: "Katamya Coast" },
  { name: "Acrow" },
  { name: "Compound Pay Central SomaBay" },
  { name: "Jasmine Palace Resort" },
  { name: "Al Bostany Developments" },
  { name: "Evangelical Coptic Patriarchate" },
  { name: "Regional Bus Station - New Minia City" },
  { name: "Atom Mall" },
  { name: "Arab Evangelical Cultural Center" },
  { name: "Sharm Al Shaikh Airport" },
  { name: "Al Nozha Beach" },
  { name: "German University in Cairo" },
  { name: "Asten College" },
  { name: "Kinda Mall" },
  { name: "Bani Ebied Hospital" },
  { name: "Verona Resort - North Coast" },
  { name: "Jungle Aqua Park Resort" },
  { name: "Jaz Aquamariene Hurgada" },
  { name: "Albatros Aqua Park Resort" },
  { name: "Rixos Radamis Sharm Al Shaikh Hotel" },
  { name: "Tirana Aqua park Resort" },
  { name: "Beach Safari Nubian Resort" },
  { name: "Sale Sucre" },
  { name: "Noor For Food Industry" },
  { name: "Be Industrial" },
  { name: "Mina Plast" },
  { name: "Al Amir Tex" },
  { name: "Bakka Clothing" },
  { name: "New Tech" },
  { name: "DP World" },
  { name: "Lake View Boutiques" },
  { name: "Palm Beach Resort" },
  { name: "Nissan Gantry Center" },
  { name: "MEPCO Egypt" },
  { name: "Safaga Port- A9" },
  { name: "Al Ameen For Gilatain" },
  { name: "Al Zeiny Center" },
  { name: "Egyptian Carbonate Company" },
  { name: "Grand Aqua" },
  { name: "Tiba Berfumes" },
  { name: "Al Hazem Plast" },
  { name: "Discovery Mining" },
  { name: "Kanaan Tex" },
  { name: "Sheraton Mall" },
  { name: "National University" },
  { name: "Amana Plast" },
  { name: "Chef Food Industries" },
  { name: "Noon For Printing & Packing" },
  { name: "October Pharma" },
  { name: "Pioneers Language School" },
  { name: "Badya" },
  { name: "Zomoroda Village- North Coast" },
  { name: "Police Academy Hospital" },
  { name: "NUB - Nahda University Beni Suif" },
  { name: "Rosetex Sahl Hasheesh" },
  { name: "ICON" },
  { name: "West Gate" },
  { name: "Kahrmana Hotel" },
  { name: "Banque Misr - Mostafa Kamel Branch" },
  { name: "Kassrawy Factory" },
  { name: "Emirits Oil" },
  { name: "Crowne Residence New Cairo" },
  { name: "Porto Heliopolis" },
  { name: "Wethaq Egypt" },
  { name: "Future Of Egypt- Almaza" },
  { name: "Happy Sweet Kamara Factory" },
  { name: "Americana" },
  { name: "Royal Moderna Resort" },
  { name: "Charm Light" },
  { name: "AZHA" },
  { name: "CSU" },
  { name: "Polaris Parks" },
  { name: "South Camp Sharm El Sheikh" },
  { name: "Cleopatra Luxury Resort Makadi Bay" },
  { name: "SCZone" },
  { name: "El Sanhory Factory" },
  { name: "CAVO" },
];
